apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels: # these labels belong to deployment
    app: web
    tier: web
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: web
      tier: web
      project: roboshop
  template: # this is the pod definition
    metadata:
      labels:
        app: web
        tier: web
        project: roboshop
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx
          items:
          - key: nginx.conf
            path: nginx.conf
      containers:
      - name: catalogue
        image: "joindevops/web:{{ .Values.deployment.imageVersion }}"
        resources:
          requests:
            cpu: "50m"
            memory: "68Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: nginx-conf # name of the volume you created above
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true